version: 0.0.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 configuration: Release
  
 deploy:
   provider: NuGet
   artifact: /.nupkg/
   api_key:
     secure: d6j0MYClUTLLg2QiYeQVhiU7akN9KHHt/OqOo+W+Hk2pVkH2mtp/KtsHU3etNT4k
