version: 0.0.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 branches:
   only:
     - master
 
 configuration: Release
  
 deploy:
   provider: NuGet
   artifact: /.nupkg/
   api_key:
     secure: VNM5wnGi0PuiIXenGuDxuF+KvS30kSDa97hCQHkEE2DZ2s8bJC40DPJol7kEUQaS
