version: 0.0.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 branches:
   only:
     - main
 
 configuration: Release
