version: 0.0.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 configuration: Debug
  
 deploy:
   provider: NuGet
   artifact: /.nupkg/
   api_key:
     secure: tas6g7o5bleaFS68B8r1Hip3nDutOGGFKZT9Gm8RETKeLioLSeB0eWSajhWAfLKf
