version: 0.0.1.{build}
image: Visual Studio 2022
configuration: Debug
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet

for:

-
 configuration: Debug
  
 deploy:
   provider: NuGet
   server: https://nuget.pkg.github.com/ahwm/index.json
   artifact: /.nupkg/
   username: ahwm
   api_key:
     secure: MErt1yyJNwqUUvMN8A1Um+YGisjzNLB6F2ATZ8mmnX41DqIMn9E0TnY/tDbSoBkM
