name: build
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.1.x
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build --verbosity normal
